name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

defaults:
  run:
    shell: bash -ileo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build on loongarch64
            image: ghcr.io/wangzw/openeuler-24.03-loongarch64
          - name: Build on riscv64
            image: ghcr.io/wangzw/openeuler-24.03-riscv64
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:9

    services:
      target:
        image: ${{ matrix.image }}
        options: -e CORE=4 -e MEMORY=8 -e DISK=20 --name target --hostname target

    steps:
      - uses: actions/checkout@v4

      - name: Install tmate
        run: |
          yum install -y epel-release
          yum install -y sshpass

      - name: Wait for target instance started
        run: |
          set -eux
          
          cmd="sshpass -p vagrant ssh -F /dev/null -l root -o StrictHostKeyChecking=no -p 3957 target 'uname -a' 2>/dev/null"
          timeout 20m bash -c "until ${cmd}; do sleep 1; done"
          
          sshpass -p vagrant scp -P 3957 -r ${GITHUB_WORKSPACE} root@target:/code

      - name: "${{ matrix.name }}"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: target
          port: 3957
          username: root
          password: vagrant
          command_timeout: 240m
          script: |
            bash -eux
            cd /code
            
            yum group install -y "Development Tools"
            yum install -y apr-devel bison bzip2-devel cmake3 flex krb5-devel libcurl-devel libevent-devel 
            yum install -y libkadm5 libxml2-devel zstd-devel openssl-devel perl-ExtUtils-Embed perl-ExtUtils-MakeMaker perl-File-Compare 
            yum install -y python3 python3-devel python3-pip readline-devel rsync xerces-c-devel zlib-devel
            
            CPUS=$(grep -c ^processor /proc/cpuinfo)
            ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=`pwd`/inst
            
            make -j${CPUS}
            make -j${CPUS} install
